# Generated by Django 4.1.2 on 2022-11-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_body_post_content_remove_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
