# Generated by Django 4.1.2 on 2022-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(),
        ),
    ]
