# Generated by Django 4.1.2 on 2022-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='person',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
