# Generated by Django 4.1.2 on 2022-11-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_profile_is_following_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_following_profile',
            new_name='is_followed_by_user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_profile_owner',
            new_name='is_user',
        ),
    ]
