# Generated by Django 4.1.2 on 2022-11-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_like_user_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
