# Generated by Django 4.1.2 on 2022-11-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
