# Generated by Django 4.1.2 on 2022-11-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_followed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
