# Generated by Django 4.1.2 on 2022-11-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_profile_is_followed_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
