# Generated by Django 4.1.2 on 2022-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
