# Generated by Django 4.1.2 on 2022-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_post_is_liked_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
